name: dragonboard-edge-kernel
version: null
version-script: |
    . debian/debian.env
    dpkg-parsechangelog -l $DEBIAN/changelog -S version
summary: The Canonical snapdragon arm64 kernel
description: The Canonical snapdragon arm64 kernel
grade: stable
confinement: strict
type: kernel

parts:
  kernel:
    plugin: kernel
    source: .
    source-type: git
    kconfigflavour: snapdragon-edge
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    kernel-image-target: Image
    kernel-with-firmware: false
    override-build: |
      cp debian/scripts/retpoline-extract-one \
        $SNAPCRAFT_PART_BUILD/scripts/ubuntu-retpoline-extract-one
      snapcraftctl build
      cp $SNAPCRAFT_PART_INSTALL/dtbs/qcom/*.dtb $SNAPCRAFT_PART_INSTALL/dtbs/
  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - linux-firmware-snapdragon
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/firmware/wlan
      ln -s /run/macaddr0 $SNAPCRAFT_PART_INSTALL/firmware/wlan/
    build-packages:
      - cpio
      - libssl-dev
      - dpkg-dev
